version: '3.8'

services:
  # MySQL Database Service
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: yourdatabase
    depends_on:
      - mysql-db
    networks:
      - backend

  # Gateway Service
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: gateway
      SERVER_PORT: 8080
      USER_SERVICE_URI: http://user-service:8081
      CODE_SERVICE_URI: http://code-service:8083
    depends_on:
      - user-service
      - video-service
      - code-service
    networks:
      - backend

  # Video Service
  video-service:
    build:
      context: ./video-service
      dockerfile: Dockerfile
    container_name: video-service
    ports:
      - "8002:8002"
    networks:
      - backend

  # Code Service
  code-service:
    build:
      context: ./code-service
      dockerfile: Dockerfile
    container_name: code-service
    ports:
      - "8083:8083"
    networks:
      - backend

# Volumes for persistent data
volumes:
  mysql-data:

# Network Configuration
networks:
  backend:
    driver: bridge
